services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - ./icons:/app/public/icons
    environment:
      HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev,192.168.86.206:3000
    restart: unless-stopped