---
- name: Tune SSH server for stable VS Code Remote-SSH
  hosts: all
  become: yes

  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.apt:
        name:
          - openssh-server
          - tar
          - gzip
        state: present
        update_cache: yes

    - name: Configure SSHD to allow root login via key and keep connections alive
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        marker: "# {mark} ANSIBLE AlphaCluster SSH tuning"
        backup: yes
        block: |
          PermitRootLogin yes
          PasswordAuthentication no
          ClientAliveInterval 120
          ClientAliveCountMax 3
          MaxSessions 10
          MaxStartups 10:30:100
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted